In [6]:
import pandas as pd

#Redaing the CSV file into a DataFrame
df = pd.read_csv('car_fuel_efficiency.csv')

# Q1. Pandas version

In [20]:
pd.__version__

'2.2.2'

### Q2. Records Count

In [ ]:
df.head()

RangeIndex(start=0, stop=9704, step=1)

In [19]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

#### Q4. Missing value

In [21]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

### Q5. Max fuel effieciency

In [ ]:
df[['origin']]

origin
0     Europe
1        USA
2     Europe
3        USA
4     Europe
...      ...
9699  Europe
9700     USA
9701     USA
9702     USA
9703    Asia

[9704 rows x 1 columns]

In [7]:
# select all cars from Asia
df[df['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [38]:
df.describe()   

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [11]:
asianFuelEfficiency = df['fuel_efficiency_mpg'].max()
asianFuelEfficiency

25.96722204888372

### Q6. MEDIAN value of horsepower

In [39]:
df.horsepower.median()

149.0

In [40]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [45]:

df.fillna({'horsepower': df.horsepower.mode()}, inplace=True)

In [46]:
df.horsepower.median()

152.0

### Q7. Sum of weights

In [15]:
# select all cars from Asia
#df[df.origin == 'Asia']
df[df['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [16]:
# Select only columns vehicle_weight and model_year
vehicleWeightModelYear = df[['vehicle_weight','model_year']]
vehicleWeightModelYear

vehicle_weight  model_year
0        3413.433759        2003
1        3149.664934        2007
2        3079.038997        2018
3        2542.392402        2009
4        3460.870990        2009
...              ...         ...
9699     2981.107371        2013
9700     2439.525729        2004
9701     2583.471318        2008
9702     2905.527390        2011
9703     2908.043477        2005

[9704 rows x 2 columns]

In [17]:
# select the  first 7 values
vehicleWeightModelYear.head(7)


vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012

In [18]:
# Get the underlying NumPy array. Let's call it X
x = vehicleWeightModelYear.to_numpy()
x

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       ...,
       [2583.47131761, 2008.        ],
       [2905.52738998, 2011.        ],
       [2908.04347736, 2005.        ]])

In [19]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX
xtx = x.T.dot(x)
xtx

array([[8.98159673e+10, 5.85831378e+10],
       [5.85831378e+10, 3.92634741e+10]])

In [24]:
# Invert XTX
import numpy as np
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 4.15473853e-10, -6.19908516e-10],
       [-6.19908516e-10,  9.50404590e-10]])

In [25]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [26]:
# Multiply the inverse of XTX with the transpose of X
imt = xtx_inv.dot(x.T)
imt


array([[ 1.76515719e-07,  6.44470349e-08,  2.82848111e-08, ...,
        -1.71411517e-07, -3.94653655e-08, -3.47005459e-08],
       [-2.12356264e-07, -4.50421050e-08,  9.19396523e-09, ...,
         3.06896544e-07,  1.10102456e-07,  1.02840285e-07]])

In [27]:
# multiply imt by y. Call the result w
imt


array([[ 1.76515719e-07,  6.44470349e-08,  2.82848111e-08, ...,
        -1.71411517e-07, -3.94653655e-08, -3.47005459e-08],
       [-2.12356264e-07, -4.50421050e-08,  9.19396523e-09, ...,
         3.06896544e-07,  1.10102456e-07,  1.02840285e-07]])

In [31]:
# Use only the first 7 rows of x to match the length of y
imt7 = xtx_inv.dot(x[:7].T)
w = imt7.dot(y)
w

array([9.15440609e-05, 2.42061149e-04])

In [32]:
#What's the sum of all the elements of the result?
sum_w = w.sum()
sum_w

0.000333605209891389